package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2021-06-17T10:47:30.865-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "service", 
                  wsdlLocation = "file:/C:/Users/Oramirez/Downloads/soap-client/src/main/wsdl/Service.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class Service extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "service");
    public final static QName ServiceHttpGet = new QName("http://tempuri.org/", "serviceHttpGet");
    public final static QName ServiceHttpPost = new QName("http://tempuri.org/", "serviceHttpPost");
    public final static QName ServiceSoap12 = new QName("http://tempuri.org/", "serviceSoap12");
    public final static QName ServiceSoap = new QName("http://tempuri.org/", "serviceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Oramirez/Downloads/soap-client/src/main/wsdl/Service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Oramirez/Downloads/soap-client/src/main/wsdl/Service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServiceHttpGet
     */
    @WebEndpoint(name = "serviceHttpGet")
    public ServiceHttpGet getServiceHttpGet() {
        return super.getPort(ServiceHttpGet, ServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceHttpGet
     */
    @WebEndpoint(name = "serviceHttpGet")
    public ServiceHttpGet getServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(ServiceHttpGet, ServiceHttpGet.class, features);
    }
    /**
     *
     * @return
     *     returns ServiceHttpPost
     */
    @WebEndpoint(name = "serviceHttpPost")
    public ServiceHttpPost getServiceHttpPost() {
        return super.getPort(ServiceHttpPost, ServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceHttpPost
     */
    @WebEndpoint(name = "serviceHttpPost")
    public ServiceHttpPost getServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(ServiceHttpPost, ServiceHttpPost.class, features);
    }
    /**
     *
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "serviceSoap12")
    public ServiceSoap getServiceSoap12() {
        return super.getPort(ServiceSoap12, ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "serviceSoap12")
    public ServiceSoap getServiceSoap12(WebServiceFeature... features) {
        return super.getPort(ServiceSoap12, ServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "serviceSoap")
    public ServiceSoap getServiceSoap() {
        return super.getPort(ServiceSoap, ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "serviceSoap")
    public ServiceSoap getServiceSoap(WebServiceFeature... features) {
        return super.getPort(ServiceSoap, ServiceSoap.class, features);
    }

}
