package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2021-06-17T10:47:30.822-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "serviceHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiceHttpGet {

    @WebMethod(operationName = "Execute")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String execute(
        @WebParam(partName = "xmlCommand", name = "xmlCommand", targetNamespace = "")
        java.lang.String xmlCommand
    );
}
